### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by tnahata** [google-developer-training/android-basics-kotlin-bus-schedule-app#1]
Inside onCreate() in the StopScheduleFragment, 
busStopAdapter.submitList(viewModel.scheduleByStopName()) should be called instead as :
busStopAdapter.submitList(viewModel.scheduleByStopName(stopName))
I am not sure but most probably this is correct!

![image](https://user-images.githubusercontent.com/68173377/123610832-98da6480-d81e-11eb-95ce-7d82895d1f41.png)

**Comment by raulhaag** [comment]
i note the same problem and only make the assings if there is any arguments

**Comment by tnahata** [comment]
@raulhaag I am not sure what you mean.

**Comment by ala710** [comment]
After this fix starter App compiles fine, but crashes at runtime (I run on real device). Does anyone observe the same behavior? Thanks.

**Comment by calren** [comment]
Thanks for pointing this out! 

The issue described in the original post:
```
busStopAdapter.submitList(viewModel.scheduleByStopName()) should be called instead as :
busStopAdapter.submitList(viewModel.scheduleByStopName(stopName))
```

is the same error described in this issue: https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/32, so we'll be closing this out in favor of that one. 

The other issue described in other comments on this thread relating to accessing the database on the main thread will be tracked on this one https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/22
