### ISSUE TITLE
Missing mention of entity table name

### ISSUE THREAD

**Issue by sandeep3119** [google-developer-training/android-basics-kotlin-bus-schedule-app#10]
```
@Entity
data class Schedule(
   @PrimaryKey val id: Int,
   @NonNull @ColumnInfo(name = "stop_name") val stopName: String,
   @NonNull @ColumnInfo(name = "arrival_time") val arrivalTime: Int
)
```
as 'schedule' as table name is used in Dao class.
**@Entity(tableName="schedule") should be mentioned.**

**Comment by calren** [comment]
We've added a clarification in the codelab about why it's not necessary to specify the table name (since queries are not case sensitive), thanks for pointing out the confusion and filing the issue!
