### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by niranza** [google-developer-training/android-basics-kotlin-bus-schedule-app#11]
in StopScheduleFragment where you create the bindings, an argument should be passed into viewModel.scheduleForStopName.
the argument is obviously the stopName, but it doesn't show there in the code lab.

snippet from the code lab:
recyclerView = binding.recyclerView
recyclerView.layoutManager = LinearLayoutManager(requireContext())
val busStopAdapter = BusStopAdapter({})
recyclerView.adapter = busStopAdapter
busStopAdapter.submitList(viewModel.scheduleForStopName())

what should really be the smippet:
recyclerView = binding.recyclerView
recyclerView.layoutManager = LinearLayoutManager(requireContext())
val busStopAdapter = BusStopAdapter({})
recyclerView.adapter = busStopAdapter
busStopAdapter.submitList(viewModel.scheduleForStopName(stopName))

**Comment by calren** [comment]
Thanks for pointing this out! We'll be closing this issue in favor of this issue that describes the same error:
https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/32
