### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by huseen0** [google-developer-training/android-basics-kotlin-bus-schedule-app#13]
I don't have a build.gradle project level file

**Comment by tuxedotshirt** [comment]
In the android project view, it is listed as build.gradle (Project: Bus_Scheduler)

**Comment by calren** [comment]
Thanks @tuxedotshirt ! That is a great way to find the project level `build.gradle` file. We'll be closing this issue since it's not an error with the codelab itself.
