### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by kareemadesola** [google-developer-training/android-basics-kotlin-bus-schedule-app#15]
**The code in Number 6 requires a parameter**

```
...
recyclerView.adapter = busStopAdapter
busStopAdapter.submitList(viewModel.scheduleForStopName())
```
Instead of

```
...
recyclerView.adapter = busStopAdapter
busStopAdapter.submitList(viewModel.scheduleForStopName(stopName))
```

**Comment by calren** [comment]
Thanks for pointing this out! We'll be closing this issue in favor of this issue that describes the same error:
https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/32
