### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by crave503** [google-developer-training/android-basics-kotlin-bus-schedule-app#16]
In section 4: Create an Entitiy, it is stated, "To create an entity for the "schedule" table, in the database.schedule package, create a new file called Schedule.kt and define a data class called Schedule." 

There is not a "database.schedule" package within the Project Manager. My assumption is that it is referencing "assets/database", but this needs to be clarified.

**Comment by calren** [comment]
Thanks for pointing this out! This issue describes the same error as #7, so we'll be closing this issue in favor of that one and work on a fix in the codelab to better specify creating the database.schedule package.
