### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by Nunocky** [google-developer-training/android-basics-kotlin-bus-schedule-app#18]
step6 in page 8, it shoud be

```
-        busStopAdapter.submitList(viewModel.scheduleForStopName())
+        busStopAdapter.submitList(viewModel.scheduleForStopName(stopName))
```

**Comment by calren** [comment]
Thanks for pointing this out! We'll be closing this issue in favor of this issue that describes the same error:
https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/32
