### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by shawn-fetanat** [google-developer-training/android-basics-kotlin-bus-schedule-app#19]
Just letting you know that the package `database.schedule` doesn't exist in this project. There is only a `database` package located in the `assets` directory and no subdirectory or package named `schedule` within it. Should we just create a directory within `database` called `schedule` or create a new package altogether within `java` called `database.schdule`?

These are the instructions I'm referring to:

"Note that the SQL types used in the database are actually `INTEGER` for `Int` and `TEXT` for `String`. When working with Room, however, you should only be concerned with the Kotlin types when defining your model classes. Mapping the data types in your model class to the ones used in the database is handled automatically.

To create an entity for the "schedule" table, in the `database.schedule` package, create a new file called `Schedule.kt `and define a data class called `Schedule.`"

**Comment by citrusella** [comment]
The completed version on the main branch has it in the com.example.busschedule package.

**Comment by calren** [comment]
Thanks for pointing this out! This issue describes the same error as #7, so we'll be closing this issue in favor of that one and work on a fix in the codelab to better specify creating the database.schedule package.
