### ISSUE TITLE
Step 8: Accessing database on main thread leads to app crash

### ISSUE THREAD

**Issue by raulhaag** [google-developer-training/android-basics-kotlin-bus-schedule-app#2]
---
name: 'Android Basics: Introduction to Room and Flow issue template'
about: 'Cannot access database on the main thread.'
title: 'Android Basics: Introduction to Room and Flow'
labels: ''
assignees: ''

---

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-intro-room-flow?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-5-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-intro-room-flow#7

**In which task and step of the codelab can this issue be found?**
8 - 4. (really  9, also bad numbers on indexes)Finally, to update a list view, call submitList(), passing in the list of bus stops from the view model
8- 11 Then configure the recycler view in onCreate(). This time you just need to pass in an empty block (function) with {}. You don't actually want anything to happen when rows on this screen are tapped.

**Describe the problem**
these lines  code
busStopAdapter.submitList(viewModel.scheduleForStopName())
busStopAdapter.submitList(viewModel.fullSchedule())
java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
no sure but need to run it on corouitines? (only that way i make it work)
also the onCreate() of 8 - 11 (onViewCreated)

**Steps to reproduce?**
complete the codelabs to the poit 8 inclusive 6/12 inclusive

**Versions**
_Android Studio version:_4.2.1
_API version of the emulator:_ 28

**Additional information**

**Comment by tnahata** [comment]
@raulhaag  
Were you able to find any solution for this problem. I am facing the exact same problem and cannot resolve it.

**Comment by Biyane** [comment]
@tnahata try to go through this codelab. Maybe, you will find an answer there (https://developer.android.com/codelabs/android-room-with-a-view-kotlin#0)

**Comment by zach-ferguson** [comment]
@raulhaag 
I had this issue as well but it is resolved after completing the next step (9) in the codelab. There we add coroutine scopes around the busStopAdapter.submitList calls.

**Comment by pentiux** [comment]
Sure it's resolving on next step, cuz you adding there a coroutine when accessing database
Soz you have to add something like this:
in viewModel
```
    suspend fun fullSchedule(): List<Schedule> = withContext(Dispatchers.IO) {
        scheduleDao.getAll()
    }

    suspend fun scheduleForStopName(name: String): List<Schedule> = withContext(Dispatchers.IO) {
        scheduleDao.getByStopName(name)
    }
```
in  fragments:
```
        lifecycleScope.launch {
            busStopAdapter.submitList(viewModel.fullSchedule())
        }
        lifecycleScope.launch {
            busStopAdapter.submitList(viewModel.scheduleForStopName(stopName))
        }
```

**Comment by raulhaag** [comment]
Thanks to all that trying to help me, but i only opened this issue to inform about it and the team in charge correct it, i make it in a similar way described by @pentiux

**Comment by iulover99** [comment]
and on the step 9 when there is error in the collect function. We need to also add the 
import kotlinx.coroutines.flow.collect
in the top of the file also to fix that problem. The error message is misleading, for more info we can find in here:
https://stackoverflow.com/questions/65559153/is-kotlin-flows-collect-is-only-internal-kotlinx-coroutines-api

**Comment by hlt229** [comment]
Thanks a lot, friends!
I am facing that problem and I don't know what to do. 
Now I realized to continue the code-lab section 9.

**Comment by calren** [comment]
Thanks for pointing this out @raulhaag , and thanks to everyone chiming in with possible solutions!

The fix is indeed mentioned in a later step, but that does cause a confusing experience if you're following the codelab step by step and trying to run the app after each step. We'll be improving the instructions for the codelabs so that this issue doesn't appear if you try launching the app immediately after Step 8.

**Comment by calren** [comment]
This has now been fixed, thanks for filing! 

As a temporary solution to ensure the app can run after the initial step, we use `GlobalScope` which is later replaced with `lifecycleScope`
