### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by VRralf** [google-developer-training/android-basics-kotlin-bus-schedule-app#20]
No se puede descargar la rama starter de github
al presionar download zip siempre descarga la rama main
![Screenshot_1](https://user-images.githubusercontent.com/86448556/134103684-00e8dca4-bc1d-4237-9653-804269e2ed57.png)
![Screenshot_2](https://user-images.githubusercontent.com/86448556/134103688-ad6f6b4b-05a4-4b23-96f5-c8556f55ea87.png)

**Comment by citrusella** [comment]
This is a known issue with Github itself and not a problem with the link in the training--Github engineers are looking into how to fix it.

**Comment by calren** [comment]
This is the same issue described in https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/21, so we'll be closing out this issue in favor of the linked one.
