### ISSUE TITLE
Issue downloading `starter` branch

### ISSUE THREAD

**Issue by aredshaw** [google-developer-training/android-basics-kotlin-bus-schedule-app#21]
Whenever you try to download the starter app in GitHub, the main branch is downloaded instead. All the changes are already done for the codelab. The only way I could get around it was to copy and change the URL to say "starter" rather than "main."

**Comment by citrusella** [comment]
...I wonder if that's a Github issue, because usually when I'm on a specific branch it downloads that branch, and the URL in the codelab goes to the starter branch page. (And it downloaded the starter branch when I started-but-didn't-finish the codelab.)

**Comment by citrusella** [comment]
I think Github fixed this a few weeks ago, FWIW.

**Comment by calren** [comment]
I believe the issue is now fixed, but thanks for filing to increase awareness for other developers!
