### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by hoangtuan877** [google-developer-training/android-basics-kotlin-bus-schedule-app#23]
In section 8. Create the ListAdapter
busStopAdapter.submitList(viewModel.scheduleForStopName()) missing parameter for scheduleForStopName method.
Should to pass stopName.

**Comment by calren** [comment]
Thanks for pointing this out! We'll be closing this issue in favor of this issue that describes the same error:
https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/32

In the mean time, feel free to refer to the `main` branch which contains the correct code
