### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by saleh-ioio** [google-developer-training/android-basics-kotlin-bus-schedule-app#24]
lesson 8 :  step 6 : 
you cant run the app because you have to pass string variable to the 

viewModel.scheduleForStopName(A STRING VARIABLE MUST BE PASSED HERE !!)

**Comment by calren** [comment]
Thanks for pointing this out! We'll be closing this in favor of https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/32, which describes the same issue.

In the mean time, the `main` branch has the correct code if you would like to refer to that instead.
