### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by sbswami** [google-developer-training/android-basics-kotlin-bus-schedule-app#25]
The issue in codelab: https://developer.android.com/codelabs/basic-android-kotlin-training-intro-room-flow
[Task 8: Create the ListAdapter](https://developer.android.com/codelabs/basic-android-kotlin-training-intro-room-flow?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-5-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-intro-room-flow#7)

in step 6, last code line is `busStopAdapter.submitList(viewModel.scheduleForStopName())`, that will not work since `scheduleForStopName` required a parameter `stopName`, the correct code will be 
`busStopAdapter.submitList(viewModel.scheduleForStopName(stopName))`

**Comment by calren** [comment]
Thanks for pointing this out! We'll be closing this issue in favor of this issue that describes the same error:
https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/25
