### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by pentiux** [google-developer-training/android-basics-kotlin-bus-schedule-app#3]
```
recyclerView = binding.recyclerView
recyclerView.layoutManager = LinearLayoutManager(requireContext())
val busStopAdapter = BusStopAdapter({})
recyclerView.adapter = busStopAdapter
busStopAdapter.submitList(viewModel.scheduleForStopName())
```
last string replace for 
`usStopAdapter.submitList(viewModel.scheduleForStopName(stopName))`

**Comment by calren** [comment]
Thanks for pointing this out! We'll be closing this issue in favor of this issue that describes the same error:
https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/32
