### ISSUE TITLE
Create the ListAdapter Step: `scheduleForStopName` is missing `name` argument in Codelab

### ISSUE THREAD

**Issue by azzumw** [google-developer-training/android-basics-kotlin-bus-schedule-app#32]
Create the ListAdapter: Step 6

When setting up StopScheduleFragment.kt - inside the onViewCreated(), string argument (stopName) is not passed.

//busStopAdapter.submitList(viewModel.scheduleForStopName(stopName)) <-- missing argument.

**Comment by calren** [comment]
This has now been fixed, thanks for filing the issue and helping improve the codelab!
