### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by bestofbest1** [google-developer-training/android-basics-kotlin-bus-schedule-app#33]
BusScheduleViewModelFactory를 반환하는 create() -> BusScheduleViewModel 을 반환하는 create() 로 바뀌어야 합니다.

**Comment by osuleymanova** [comment]
@bestofbest1 
Thank you for reaching out to us. Unfortunately, we have to close the ticket due to the lack of required information.
