### ISSUE TITLE
Android Basics: Introduction to Room and Flow (ViewRootImpl$CalledFromWrongThreadException)

### ISSUE THREAD

**Issue by xmakina** [google-developer-training/android-basics-kotlin-bus-schedule-app#35]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-intro-room-flow?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-5-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-intro-room-flow#7

**In which task and step of the codelab can this issue be found?**
Step 7, "Take a moment to run the app and you should see a list of arrival times"

**Describe the problem**
On running the app in the emulator, it terminates immediately with the following error in Logcat:
```
2021-11-19 10:42:59.802 5772-5798/com.example.busschedule E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.example.busschedule, PID: 5772
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8798)
        ...
        at com.example.busschedule.FullScheduleFragment$onViewCreated$1.invokeSuspend(FullScheduleFragment.kt:75)
        ...
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Steps to reproduce?**
Follow tutorial as described.

**Versions**
_Android Studio version:_ Android Studio Arctic Fox | 2020.3.1 Patch 3
_API version of the emulator:_  30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
The referenced code block which is causing the crash:
![image](https://user-images.githubusercontent.com/1357791/142610615-28753499-0edd-4db4-abc9-98efbc742d9f.png)

**Comment by osuleymanova** [comment]
@xmakina 
Thank you for reaching out to us and providing the code snippet where the issue was reproduced. 
Please follow the steps in the comments. As the result the code should look like this below:
![Screen Shot 2022-04-05 at 4 48 06 PM](https://user-images.githubusercontent.com/86437155/161869250-eafd78ec-6da0-47ee-9854-8c025059ccc3.png)
