### ISSUE TITLE
Occasional crash in FullScheduleFragment.kt & StopScheduleFragment.kt  due to UI updation from background thread

### ISSUE THREAD

**Issue by mlnoone** [google-developer-training/android-basics-kotlin-bus-schedule-app#36]
In FullScheduleFragment.kt the line
`GlobalScope.launch(Dispatchers.IO) {
            busStopAdapter.submitList(viewModel.fullSchedule()) 
  }`
In StopScheduleFragment.kt the line
`GlobalScope.launch(Dispatchers.IO) {busStopAdapter.submitList(viewModel.scheduleForStopName(stopName))  }`

sometimes crash. Resolved by calling submlitList using Dispatchers.main:

`GlobalScope.launch(Dispatchers.IO) {`
            `val fullSchedule = viewModel.fullSchedule()`
           `launch(Dispatchers.Main) {busStopAdapter.submitList(fullSchedule)}`
     `}`

**Comment by ethanonfire** [comment]
yes, my app sometimes crash too because of this. i think you have solved the problem.

**Comment by mlnoone** [comment]
👍
