### ISSUE TITLE
.collect() does not work without import kotlinx.coroutines.flow.collect

### ISSUE THREAD

**Issue by mlnoone** [google-developer-training/android-basics-kotlin-bus-schedule-app#37]
[As mentioned here: https://stackoverflow.com/questions/65559153/is-kotlin-flows-collect-is-only-internal-kotlinx-coroutines-api](https://stackoverflow.com/questions/65559153/is-kotlin-flows-collect-is-only-internal-kotlinx-coroutines-api)

**Comment by osuleymanova** [comment]
@mlnoone 
The ticket is closed as no further clarification was provided. Please feel free to re-open it by providing the required details: codelab url, screenshots or the code snippet.
