### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by pentiux** [google-developer-training/android-basics-kotlin-bus-schedule-app#4]
Create list adapter 
at the end 
"Now that you've set up the adapter, you're done integrating Room into the Bus Schedule app. Take a moment to run the app and you should see a list of arrival times. Tapping on a row should navigate to the detail screen."
Got error 
```
FATAL EXCEPTION: main
    Process: com.example.busschedule, PID: 22917
    java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
```
in main branch
```
        lifecycle.coroutineScope.launch {
            viewModel.fullSchedule().collect() {
                busStopAdapter.submitList(it)
            }
        }
```
But in course there is none
```
        recyclerView.adapter = busStopAdapter
        busStopAdapter.submitList(viewModel.fullSchedule())
```

soz you have to use something like this:
```
        lifecycleScope.launch {
            busStopAdapter.submitList(viewModel.fullSchedule())
        }
```
and in viewModel sort of:
```
    suspend fun fullSchedule(): List<Schedule> = withContext(Dispatchers.IO) {
        scheduleDao.getAll()
    }
```

**Comment by brunomateus** [comment]
I find the same problem, but you don't need to use `withContext(Dispatchers.IO)` since Room handle the decision of using the correct Thread internally.
Source: https://medium.com/androiddevelopers/coroutines-on-android-part-i-getting-the-background-3e0e54d20bb, https://medium.com/androiddevelopers/room-coroutines-422b786dc4c5 .

**Comment by jamessa** [comment]
Same issue here. My solution is by adding `.allowMainThreadQueries()` in `AppDatabase`

```Kotlin
.createFromAsset("database/bus_schedule.db")
.allowMainThreadQueries()
.build()
```

source https://stackoverflow.com/a/44857008/99702
document https://developer.android.com/reference/kotlin/androidx/room/RoomDatabase.Builder#allowMainThreadQueries()

**Comment by lbarqueira** [comment]
I found the same issue. 
"    --------- beginning of crash
2021-08-24 17:24:44.352 10084-10084/com.example.busschedule E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.busschedule, PID: 10084
    java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time."
I will try to solve with your solutions.
Thanks

**Comment by calren** [comment]
Thanks for pointing this! This issue https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/2 describes the same error, so we'll be closing out this one in favor of that. That issue also has people pointing out the solution to the problem if you want to resolve the error.
