### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by blackcrown01** [google-developer-training/android-basics-kotlin-bus-schedule-app#41]
Hello i started learning kotlin like 4 monnths ago and i reached this unit about SQL and dataBase but i've noticed along the journy that the courses are not updated tpo my current version of andriod studio and i listed some of the problems or isuues i faced : 

1- the imports are automatic but not alawys the right ones 
2- the gradel version always not up to date which causes some issues during compling and building apps
3-sometimes but not always the steps on the lesson can misslead instad of guid you throw the lesson 
4- id the same exact steps but i don't get the same results as the solution codes 

if any one can help it will be much apreshiated

**Comment by osuleymanova** [comment]
@blackcrown01 
Thank you for reaching out to us. We totally understand your frustration. So the following actions were taken: Gradle and dependencies versions in branches were updated. The content of the codelab was updated accordingly and will be published soon.
Hope no more issues will be faced with.
