### ISSUE TITLE
Option to hide the top bar or make it thinner

### ISSUE THREAD

**Issue by HubKing** [google-developer-training/android-basics-kotlin-bus-schedule-app#42]
The document font is too small, so if I zoom the page in, the top bar gets thicker, taking up limited vertical space of modern wide-screen monitors. I do not think the top bar serves any useful features for the most people. How about providing a feature to hide that top bar?

![image](https://user-images.githubusercontent.com/10900489/148892108-7cd98de4-67c1-4576-bbcf-b9b9909ceb19.png)

**Comment by osuleymanova** [comment]
Hello @HubKing,

Thank you for reaching out to us and sharing your feedback. We'll keep it in mind for the future maintenance of  codelabs.
