### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by angelomarzocchi** [google-developer-training/android-basics-kotlin-bus-schedule-app#43]
The base project just won't build.
It says "Unable to load class 'build_4ei2j6orgipxqxl9qkqwlur0o'.

This is an unexpected error. Please file a bug containing the idea.log file."

**Comment by osuleymanova** [comment]
@angelomarzocchi 
Thank you for reaching out to us. Recently the repo and content were updated. If you still face with the same issue please feel to re-open the ticket by providing full descriptive details and screenshots.
