### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by CarlBosch** [google-developer-training/android-basics-kotlin-bus-schedule-app#45]
First of all thank you very much for the elaborate tutorial on Room in Android.

The code of FullScheduleFragment didn't compile on my side when I changed the code to use Flow.

Step:

[9. Respond to data changes using Flow]
When replacing the existing code to load the data with the following I had an error saying **Unresolved reference: collect**

lifecycle.coroutineScope.launch {
   viewModel.fullSchedule().collect() {
       busStopAdapter.submitList(it)
   }
}

So after looking at the solution code I found I had to add the **import kotlinx.coroutines.flow.collect** -- this was not a suggestion of Android Studio. So I suggest you add this instruction in the tutorial.

Also it is not clear at all for me lifecycle is and why we would need to use it but I understand this aspect might go further than what the tutorial is intended to.

Thanks again

**Comment by huss-a** [comment]
I've added the import but I still get the same error.

**Comment by pd95** [comment]
Thanks for your issue. This helped me in resolving the same problem I encountered today!
Android Studio is not proposing to import the type but is complaining about an "internal API use" as shown below:
<img width="904" alt="Screenshot with error" src="https://user-images.githubusercontent.com/25307503/162738378-154ecaca-25a8-4b2b-8603-69ead419d5b0.png">

These **import**s are anyway somehow strange to me (coming from iOS) especially if you have multiple possible source packages... Sometimes I end up using "trial and error" strategy to find the correct import.
