### ISSUE TITLE
Update dependencies to resolve app build errors on Mac M1

### ISSUE THREAD

**Issue by rock-chock** [google-developer-training/android-basics-kotlin-bus-schedule-app#46]
### In which task and step of the codelab can this issue be found?
Step 7 

### Describe the problem
App doesn't build due to outdated dependencies on Mac M1

### Steps to reproduce?

*Pre-requisites*:
- Mac with M1 chip with Android Studio

1. Download the starter code and complete steps until step 7, then try to build the app
OR 
Download the solution code and try to build the app

### Notes
The starter app builds just fine until implementing Step 7 where we add everything to retrieve data from database. 

I've downloaded the solution code from `main` branch and tried to build the app - I got the same errors. 

I was able to successfully run solution code and then the starter code after updating the dependencies and manifest file.

### Solution
Update gradle and manifest files to use the latest stable versions of dependencies. 

In `build.gradle (Project)`: 
```
buildscript {
    ext {
        kotlin_version = "1.6.10" // old version: 1.3.72
        room_version = '2.4.1' // old version: 2.3.0 
...
    }
}
```

In `build.gradle (Module)`:
```
android {
    compileSdkVersion 31 // old version: 30
    ...
    defaultConfig {
         ...
         targetSdkVersion 31 // old version: 30
       ...
     }
}
```

In `AndroidManifest.xml`:
```
<activity
            android:name="com.example.busschedule.MainActivity"
            android:exported="true" > // add this line 
```

I've also upgraded gradle when Android studio suggested this, but I couldn't capture all the details of the automated changes.

**Comment by osuleymanova** [comment]
@rock-chock 
Thank you for reaching out to us. The repo branches and the codelab content accordingly are updated and will be published soon.
