### ISSUE TITLE
Data changes using Flow: Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by mcchots** [google-developer-training/android-basics-kotlin-bus-schedule-app#49]
In the instructions for changing the FullScheduleFragment it says:

> Replace the line.

`busStopAdapter.submitList(viewModel.fullSchedule())`
> With this code that uses the flow returned from `fullSchedule()`.

````
lifecycle.coroutineScope.launch {
   viewModel.fullSchedule().collect() {
       busStopAdapter.submitList(it)
   }
}
````

When it should say to replace the entire GlobalScope function.
The same goes for the StopScheduleFragment section

**Comment by ShahsTestingZone** [comment]
In addition to this I think there needs to be an extra step to say that import of "import kotlinx.coroutines.flow.collect" is required or else it will show a red error on the collect() function, without any clear way to understand what you need to do to resolve the error.  

Personally I went on the solution code to check this first before troubleshooting any further.

**Comment by roozbehzarei** [comment]
> In addition to this I think there needs to be an extra step to say that import of "import kotlinx.coroutines.flow.collect" is required or else it will show a red error on the collect() function, without any clear way to understand what you need to do to resolve the error.
> 
> Personally I went on the solution code to check this first before troubleshooting any further.

You're right. I got the same error and the codelab doesn't mention the need of the said library.

**Comment by Wavey1287** [comment]
This particular codelab was written very poorly.  Without the solution code to check, there's no way anyone could finish this by the instructions provided.

**Comment by osuleymanova** [comment]
@mcchots, @roozbehzarei , @Wavey1287 
Thank you for contacting us and providing your feedback. 
To get more information how to enable auto imports, please refer to the codelab:
https://developer.android.com/codelabs/basic-android-kotlin-training-create-dice-roller-app-with-button?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-create-dice-roller-app-with-button#3

![Screen Shot 2022-09-22 at 4 43 42 PM](https://user-images.githubusercontent.com/86437155/192026497-a212759b-d348-4d70-a6e5-6d75739c55b2.png)

**Comment by Wavey1287** [comment]
@osuleymanova Thanks but the real issue is you all didn't check the instructions were up-to-date and accurate.  You need to explicitly state what imports are needed and when.  Usually, in other codelabs, you all do that fine.  These instructions were just not up to par.  They were not well written and this one import was not the only issue I ran into on this codelab.  I think you all should have one of your juniors try to run through the steps and make sure there still aren't any holes in the codelab.

**Comment by mcchots** [comment]
Nor does it answer the issue I raised.

**Comment by osuleymanova** [comment]
@Wavey1287 
Thanks for your feedback. We are working on repos and codelab content updates.
