### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by BankSinatra** [google-developer-training/android-basics-kotlin-bus-schedule-app#53]
It seems as if there's a typo in step 6 of the "Introduction to Room and Flow" Codelab.

> "As the ViewModel class BusScheduleViewModel needs from is meant to be lifecycle aware, it should be instantiated by an object that can respond to lifecycle events."
![image](https://user-images.githubusercontent.com/51966182/161888696-134e15de-47e4-481b-a3ad-b6ed753e0178.png)

**Comment by BankSinatra** [comment]
I forgot to add that the wording in that part of the text was really confusing and it took a while to be able to decipher what was really being talked about

**Comment by osuleymanova** [comment]
@BankSinatra 
Thank you for reaching out to us. Our apologies for the confusion caused. The content was edited and published:

![Screen Shot 2022-07-12 at 4 25 41 PM](https://user-images.githubusercontent.com/86437155/178615083-f8a68d65-1f78-4bc7-bb25-d7d98a658d49.png)
