### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by roozbehzarei** [google-developer-training/android-basics-kotlin-bus-schedule-app#54]
This codelab is using **ViewModelProvider** class and the **Factory design pattern** while both are never mentioned in previous codelabs nor properly introduced in this one. Also there are many grammar/typo mistakes present.
The mentioned problems make understanding this codelab difficult for learners.

**Comment by osuleymanova** [comment]
@roozbehzarei 
Thank you for contacting us and sharing your feedback. Could you please be more specific about your concern and grammar mistakes/typos?

**Comment by xascar** [comment]
@roozbehzarei yeah, for me was kind of confusing the explanation about why "can't just instantiate a BusScheduleViewModel directly", codelab say:

"If you instantiate it directly in one of your fragments, then your fragment object will have to handle everything, including all the memory management" but then what happened with Shared ViewModel in cupcake ordering app(Android basics kotlin/Unit 3/pathway 4/Activity 2)?  There I built the cupcake ordering app, and use a shared ViewModel to share data between the fragments of the same activity but now it doesn’t make sense. I guess it could be a good idea make that reference @osuleymanova
