### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by ValdirCastaldelliJr** [google-developer-training/android-basics-kotlin-bus-schedule-app#55]
GlobalScope.launch(Dispatchers.IO) is causing an exception [Only the original thread that created a view hierarchy can touch its views.] with Kotlin version "1.6.21" this can cause some confusion in inexperienced developers in the basic training. This issue is fixed when we use Flow later in the same training. 

I think is good to have some advice in the course about this error.

**Comment by osuleymanova** [comment]
@ValdirCastaldelliJr 
Thank you for contacting us and sharing your feedback. We'll keep in mind your suggestion.
