### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by TenHorizons** [google-developer-training/android-basics-kotlin-bus-schedule-app#57]
In chapter 6, the sentance is a little hard to read seemingly because of typos. 
![image](https://user-images.githubusercontent.com/40300779/168908609-457db89b-c4fc-405b-ae36-bee662e67d1b.png)

Also the boilerplate code at the end of chapter 6 is quite hard to understand. I think it would be nice to add a bit of explanation.
![image](https://user-images.githubusercontent.com/40300779/168909420-8d46749b-fcf6-45ce-9a9d-714987edf811.png)

**Comment by osuleymanova** [comment]
@TenHorizons 
Thank you for reaching out to us. The codelab content was updated and will be published soon:

![Screen Shot 2022-07-12 at 2 29 47 PM](https://user-images.githubusercontent.com/86437155/178605330-229549e8-a942-4493-962e-5d8c21ae0037.png)

**Comment by osuleymanova** [comment]
@TenHorizons 
Thank you for reaching out to us. The codelab content is edited and will be published soon:

![Screen Shot 2022-07-12 at 3 21 32 PM](https://user-images.githubusercontent.com/86437155/178605648-cc07d98e-6188-4a61-9484-7cd1f474eace.png)
