### ISSUE TITLE
Android Basics: Introduction to Room and Flow - grammar

### ISSUE THREAD

**Issue by nichojo89** [google-developer-training/android-basics-kotlin-bus-schedule-app#58]
In the "Define the ViewModel" step, there is a sentence that reads
_"As the ViewModel class BusScheduleViewModel needs from is meant to be lifecycle aware, it should be instantiated by an object that can respond to lifecycle events."_

Should this instead be?
_"As the ViewModel class BusScheduleViewModel is meant to be lifecycle aware, it should be instantiated by an object that can respond to lifecycle events."_

**Comment by shepardsn** [comment]
I agree.  Similarly, the sentence after it reads:

_If you instantiate it directly in one of your fragments, then your fragment object will have to **handle everything all the memory management**, which is beyond the scope of what your app's code should do._ 

and perhaps should be:

_If you instantiate it directly in one of your fragments, then your fragment object will have to **handle everything, including all the memory management,** which is beyond the scope of what your app's code should do._

**Comment by osuleymanova** [comment]
@nichojo89 , @shepardsn 
Thank you for reaching out to us. Your typo fix suggestions were reviewed and will be published soon:

![Screen Shot 2022-07-12 at 3 11 43 PM](https://user-images.githubusercontent.com/86437155/178604327-8e64ccaf-2f4d-472d-996e-8f4c5f1a896c.png)
