### ISSUE TITLE
Update Kotlin version to be compatible with latest Android Studio version

### ISSUE THREAD

**Issue by Straightholdup** [google-developer-training/android-basics-kotlin-bus-schedule-app#6]
8. Create the ListAdapter

Mistake 1:
Then configure the recycler view in onCreate()
We should configure the recycler view in onViewCreated()

Mistake 2:
busStopAdapter.submitList(viewModel.scheduleForStopName())
We should pass stopName to scheduleForStopName

Suggestion:
At the beginning of the tutorial add a note that needs to change the version of Kotlin in the Gradle. Android Studio did not work correctly for me

**Comment by calren** [comment]
> Then configure the recycler view in onCreate() ... We should configure the recycler view in onViewCreated()

This has been fixed to refer to `onViewCreated()` instead.

> We should pass stopName to scheduleForStopName

This is the same issue described in https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/32, and we'll be using that issue to track progress.

> At the beginning of the tutorial add a note that needs to change the version of Kotlin in the Gradle. Android Studio did not work correctly for me
Good idea! We'll be updating the code to do that and will keep this issue to track the progress.

**Comment by osuleymanova** [comment]
@Straightholdup 
Thank you for reaching out to us. The Kotlin and Gradle versions are updated.
