### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by pgilhead** [google-developer-training/android-basics-kotlin-bus-schedule-app#61]
This example would be improved with more explanation for each new section of code, especially on Step 8, to say why each step is needed. Currently it's just saying effectively "write this code, then write this code, then this, etc.." and the application may work at the end but without enough clarity to really explain what is happening. This is based on having worked through the previous tutorials on view models etc.

**Comment by SonOfaSleep** [comment]
Yep, more explanations would be appreciated. 
For now it's more like "Do it yourself" book with instruction that you ctrl+c - ctrl+v

**Comment by osuleymanova** [comment]
@pgilhead 
Thank you for contacting us and providing your feedback. The main goal of the codelab is to provide basic knowledge, initiate the real challenging environment while writing the code, and give the right direction for deeper self-learning.
