### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by sammorton11** [google-developer-training/android-basics-kotlin-bus-schedule-app#62]
lifecycle.coroutineScope.launch {
            viewModel.scheduleForStopName(stopName).collect() {
                busStopAdapter.submitList(it)
            }
        }

this doesn't work

**Comment by RomanRC99** [comment]
import kotlinx.coroutines.flow.collect

**Comment by osuleymanova** [comment]
Duplicate of #59, #45
