### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by grvknight** [google-developer-training/android-basics-kotlin-bus-schedule-app#63]
"FullScheduleFragmentDirections" showing error as Unresolved reference 

and " .navigate(action)" as Overload resolution ambiguity 

But the project builds successfully.

**Comment by osuleymanova** [comment]
@grvknight 
Please provide the required details (codelab URL, step, visual proof of the error message... )while reporting an issue so that we can help you with troubleshooting.

**Comment by osuleymanova** [comment]
The issue is closed as no further clarification of it was provided.
