### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by Eagle528** [google-developer-training/android-basics-kotlin-bus-schedule-app#64]
This whole Kotlin thing went from 0 to a 100 real quick.
Every lesson until now was understandable, even if I didn't understand something that I wrote, a quick Googleing job would help, but things happening in here are high above my knowledge, knowledge that I gained from previous classes. Description of steps is very poor, the only thing I can do is a lot of retyping and almost no understanding of what I'm doing.

**Comment by Caitiff5** [comment]
exactly. For such an important topic, the explanations for why and where are rare.
There is no explanation as in why some steps are needed.
