### ISSUE TITLE
Missing database.schedule package as described in codelab

### ISSUE THREAD

**Issue by DannR74** [google-developer-training/android-basics-kotlin-bus-schedule-app#7]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-intro-room-flow?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-5-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-intro-room-flow#3

**In which task and step of the codelab can this issue be found?**
4

**Describe the problem**
"To create an entity for the "schedule" table, in the database.schedule package, create a new file called Schedule.kt and define a data class called Schedule."

- There is no database.schedule package in the Starter app

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot (8)](https://user-images.githubusercontent.com/80080821/125167965-2dbf5500-e171-11eb-86f6-7bc00f411942.png)

**Comment by calren** [comment]
This has now been fixed, thanks for filing!
