### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by stef-ang** [google-developer-training/android-basics-kotlin-bus-schedule-app#76]
I got error "Only the original thread that created a view hierarchy can touch its views." when executing
```
GlobalScope.launch(Dispatchers.IO) {
   busStopAdapter.submitList(viewModel.fullSchedule())
}
```
[(Step 8)](https://developer.android.com/codelabs/basic-android-kotlin-training-intro-room-flow?hl=en#7)
we need to switch dispatcher to `Dispatchers.Main`:
```
lifecycleScope.launch(Dispatchers.IO) {
    val schedules = viewModel.fullSchedule()
    withContext(Dispatchers.Main) {
        busStopAdapter.submitList(schedules)
    }
}
```

**Comment by Mahmoud-Ibrahim-750** [comment]
@stef-ang Thanks for sharing the solution.
