### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by NardenAyad** [google-developer-training/android-basics-kotlin-bus-schedule-app#77]
I have an error here, I can't solve it.

E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.example.busschedule, PID: 15410
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

in this line, in class FullScheduleFragment

            busStopAdapter.submitList(viewModel.fullSchedule())

**Comment by Mahmoud-Ibrahim-750** [comment]
@NardenAyad check this issue #76 for a solution.
