### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by sianghao** [google-developer-training/android-basics-kotlin-bus-schedule-app#8]
Hi, the starter project didn't have the "database.schedule package", as required in part 4 - Create an Entity.

**Comment by calren** [comment]
Thanks for pointing this out! This issue describes the same error as https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/7, so we'll be closing this issue in favor of that one and work on a fix in the codelab to better specify creating the `database.schedule` package.
