### ISSUE TITLE
Codelab refers to package that doesn't exist (possible duplicate)

### ISSUE THREAD

**Issue by sianghao** [google-developer-training/android-basics-kotlin-bus-schedule-app#9]
Following the project structure from the solution code... in Step 7's final step 7, the path to add in the XML file doesn't exist. The project structure from the tutorial and solution is different - they're both messed up.

**Comment by calren** [comment]
I don't believe there's a step to add any XML files in the codelab, but perhaps you're referring to the step to add the `Schedule` class? In that case, this issue describes the same error: https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/7 and we can close out this one in favor of the linked issue.
