### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by macsftech** [google-developer-training/android-basics-kotlin-bus-schedule-app#97]
In Step -3
If a user like me creates a project using the Android Studio tool itself, it is recommended to use Kotlin DSL (.kts) and in this step: `ext {
   kotlin_version = "1.6.20"
   nav_version = "2.4.1"
   room_version = '2.4.2'
}` this will not be possible, so it is extremely useful to inform users that other ways of obtaining the same result that with ext do not work

**Comment by jlulovics** [comment]
thank you for your feedback. this content has been deprecated. please visit https://developer.android.com/courses/android-basics-compose/course for the latest recommended best practices in android development.
